name: Run Golf Leaderboard Scraper

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Existing Database (if available)
        uses: actions/download-artifact@v4
        with:
          name: pga-data
          path: ./

      - name: Check if database exists
        run: ls -lah pga-data.db || echo "⚠️ No existing database found, creating a new one."

      - name: Run Scraper
        run: python scraper.py

      - name: Upload Updated SQLite Database
        uses: actions/upload-artifact@v4
        with:
          name: pga-data
          path: pga-data.db
