name: Run Golf Leaderboard Scraper

on:
  schedule:
    - cron: '*/20 * * * *' # Runs every 20 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest # Use a Linux environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug: Print Working Directory
        run: |
          pwd
          ls -la

      - name: Run Scraper
        run: python scraper.py

      - name: Upload SQLite Database
        uses: actions/upload-artifact@v4
        with:
          name: pga-data
          path: pga-data.db  # Ensure this is the correct path where the db is saved
